version: '3.8'

services:
  app:
    platform: linux/x86_64
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://simplon-app:example@db:5432/simplon?schema=public

    command: npm run start:dev
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: simplon
      POSTGRES_USER: simplon-app
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'

volumes:
  postgres_data:
